#
#    __                          __
#   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/tegonal/github-commons
#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        It is licensed under Creative Commons Zero v1.0 Universal
#  \__/\__/\_, /\___/_//_/\_,_/_/         Please report bugs and contribute back your improvements
#         /___/
#                                         Version: v0.6.0
#
###################################
name: Cleanup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup Sources
        run: ./scripts/cleanup-on-push-to-main.sh
      - name: Create Pull Request if necessary
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-cleanup
          title: Cleanup
          commit-message: cleanup sources
          body: Looks like someone forgot to run some commands before committing. I did it for them :)
          delete-branch: true
          push-to-fork: ${{ secrets.FORK_FOR_PR }}
